### PR TITLE
Adding Zrix Time Tracking

### PR DESCRIPTION
**Pull request by amit-zrix**
Need to add the Zrix Time Tracking for Basecamp3

### CODE REVIEW

**Comment by rosa** [comment]
Hey @amit-zrix, thanks for sending this pull request. Just two things before being able to merge:

- I'm not completely familiar with how your software works. Does it implement any type of employee monitoring and surveillance? That is, is your app compliant with these specific terms of use for our API?

> Third parties may not access and employ the API if the functionality is part of an application that remotely records, monitors, or reports a Service user’s activity other than time tracking, both inside and outside the applications. The Company, in its sole discretion, will determine if an integration service violates this bylaw. A third party that has built and deployed an integration for the purpose of remote user surveillance will be required to remove that integration.

- Could you make sure your changes only add your integration to `integrations.yml` and don't modify any of the previous integrations already present?

**Comment by amit-zrix** [comment]
Hi Rosa,

- We are not doing employee monitoring and surveillance. We only Increase Business Productivity By Tracking Work Time.

- Yes I confirmed that other previous integration not affected by our changes.

**Comment by rosa** [comment]
Cool, thank you!

Could you modify your pull request to remove [these changes](https://github.com/basecamp/bc3-integrations/pull/156/files#diff-11d02858051b8cfef08d288401822da0L16-L386)?

**Comment by amit-zrix** [comment]
Hi Rosa,

Can you check review again

**Comment by amit-zrix** [comment]
Hi Rosa,

When can my tools visible for public on url https://basecamp.com/extras?

Thanks
Amit

**Comment by rosa** [comment]
It'll be visible later today 😊

**Pull request merged**
