### PR TITLE
Adding Tracked

### PR DESCRIPTION
**Pull request by trackedsupport**

### CODE REVIEW

**Comment by javan** [comment]
Thanks, your pull request looks good. Does your integration only work as a Chrome extension? It's not clear from your website. I also noticed that the Privacy and Terms links in the footer don't work.

**Comment by trackedsupport** [comment]
Yes, currently it works as a Chrome extension and there are plans to add it to other browsers as well. Thanks, I have updated the privacy and terms.

**Comment by trackedsupport** [comment]
Also I added that it only works as a Chrome extension on the index marketing page too. Thanks for your help!

**Comment by javan** [comment]
Cool, thanks. I suggest showing an actual browser in your screenshots too. Right now the rounded corners make it look like our Mac app, but your integration won't work there.

Example: 
screen shot 2017-07-03 at 1 54 11 pm

**Comment by trackedsupport** [comment]
Hey @javan how long until we get added to the basecamp.com/extras page?

**Comment by javan** [comment]
It's listed now!

**Pull request merged**
