### PR TITLE
Add Hubstaff integration

### PR DESCRIPTION
**Pull request by raulpopadineti**
- add Hubstaff icon
- add integration details to YAML file

### CODE REVIEW

**Comment by raulpopadineti** [comment]
@javan FYI.

**Comment by javan** [comment]
Is your BC3 integration up and running? Asking because https://hubstaff.com/time_tracking_for_basecamp only has screenshots of BC2 and BC1.

**Comment by raulpopadineti** [comment]
It's in staging now, so probably today or tomorrow it will go live. I'll ping you once again when it's up&running.

**Comment by raulpopadineti** [comment]
@javan the integration is live and the URL is updated. Let me know when you have time to merge this. 

Thanks!

**Comment by javan** [comment]
Thanks!

**Pull request merged**
