### PR TITLE
Update integrations.yml

### PR DESCRIPTION
**Pull request by sscarlin**
Added Zapier

### CODE REVIEW

**Comment by javan** [comment]
Forget to add your icon file? See https://github.com/basecamp/bc3-integrations#add-your-integration for the required file type and size.

**Comment by sscarlin** [comment]
Hi Javan, When I click ‘upload files’ it says ‘uploads are disabled’ because I need push access. Thanks, Carlin

**Comment by sscarlin** [comment]
Javan - created another pull request with the logo. Let me know if you need anything else!

**Comment by javan** [comment]
Got it, thanks! I pieced them together. :)

**Comment by sscarlin** [comment]
Thanks!

**Pull request closed without merging**
