### PR TITLE
replace instabug logo with new logo

### PR DESCRIPTION
**Pull request by azamzamy**

### CODE REVIEW

**Comment by azamzamy** [comment]
@rosa Hey there Rosa,
I was wondering if there is any update on this. Could you help me out?

Thanks a lot.

**Comment by rosa** [comment]
Ah, @azamzamy, sorry! I missed this pull request last week, wasn't my intention. The new logo looks good, I'll get it merged right away.

**Comment by rosa** [comment]
Your new logo is now live 🙌

**Comment by azamzamy** [comment]
@rosa No worries! Much appreciated 🙏

**Pull request merged**
