### PR TITLE
Added Jitbit integration

### PR DESCRIPTION
**Pull request by alex-jitbit**
Added Jitbit help desk software integration

### CODE REVIEW

**Comment by alex-jitbit** [comment]
Thanks! How could I overlook that, gosh. Updated the branch, sorry about that

**Comment by alex-jitbit** [comment]
@rosa hope I'm not PITA, but how often do you guys update your list at https://basecamp.com/extras ? ;)

**Comment by rosa** [comment]
Oops, sorry @alex-jitbit! We'd normally update it right away after merging the PR but I couldn't do that back when I merged yours for unrelated reasons, then it completely slipped through the cracks! So sorry, will get it on `/extras` shortly 🙏

**Comment by rosa** [comment]
Done, and sorry again for the long wait!

**Comment by alex-jitbit** [comment]
@rosa awesome thanks!! We also listed you guys at https://www.jitbit.com/helpdesk/basecamp/

**Pull request merged**
