### PR TITLE
Added TrackingTime

### PR DESCRIPTION
**Pull request by trackingtime**

### CODE REVIEW

**Comment by trackingtime** [comment]
Added TrackingTime to the list of integrations. Thanks!

**Comment by rosa** [comment]
Hi @trackingtime! Sorry for the delay replying. Your changes look good to me. I only have a question: I have been looking at [trackingtime.co](https://trackingtime.co/) and I think the answer is no, but I'm not completely familiar with how your software works. Does it implement any type of employee monitoring and surveillance? That is, is your app compliant with these specific terms of use for our API?

> Third parties may not access and employ the API if the functionality is part of an application that remotely records, monitors, or reports a Service user’s activity other than time tracking, both inside and outside the applications. The Company, in its sole discretion, will determine if an integration service violates this bylaw. A third party that has built and deployed an integration for the purpose of remote user surveillance will be required to remove that integration.

**Comment by trackingtime** [comment]
Hi Rosa, thanks for reaching out!
We don’t monitor user activity, neither use Basecamp API to do that 👌

Cheers
Eric

**Comment by rosa** [comment]
Wonderful, thank you so much for confirming!

**Pull request merged**
