### PR TITLE
Aureum integration

### PR DESCRIPTION
**Pull request by hutsonphd**
Added to icons and integreations.yml

### CODE REVIEW

**Comment by rosa** [comment]
Hey @hutsonphd, thanks for opening this! Is there any page or any place where you explain in more detail what the integration does? I've been browsing https://www.aureumdata.com but it's not clear to me.

**Comment by hutsonphd** [comment]
I didn’t realize you needed that. Do I need to make a landing page or video or just send you an explanation?

Andrew Hutson
***@***.***

**Comment by rosa** [comment]
Thanks @hutsonphd! It'd be something that customers can check out to see how the integration works. It can be a landing page (like [this one from Harvest](https://www.getharvest.com/integrations/basecamp)) or perhaps a section in your help pages (like [this one from Saber Feedback](https://help.saberfeedback.com/article/29-integrating-saber-feedback-with-basecamp)) or a generic integrations page where you include other integrations (like [this one from timeneye](https://www.timeneye.com/integrations/)) or even an explanation embedded into another page (like [this one from TaskBill](https://taskbill.io/?utm_source=basecamp)).

**Comment by hutsonphd** [comment]
Hi Rosa:
So thankful for all the examples you shared. Check out our shiny new integrations page. Let me know if you need anything more. Very open to feedback.

https://www.aureumdata.com/integrations

Cheers,
Andrew

**Comment by hutsonphd** [comment]
Hi @rosa : Are there any other changes needed before you can accept this PR?

**Comment by rosa** [comment]
Hi @hutsonphd, so sorry for the delay! I missed the notification. The Basecamp logo you're using is for Basecamp 2, though, and this repo is for Basecamp 3. Is your integration for Basecamp 2?

**Comment by hutsonphd** [comment]
No worries @rosa. The integration is for Basecamp 3. Can you share acceptable logos for BC3? I can make the changes today.

**Comment by rosa** [comment]
Yes! You can find it [here](https://basecamp.com/about/press), under _Download the Basecamp logo_ or under _Download the entire Basecamp Press Kit_.

**Comment by rosa** [comment]
Also, @hutsonphd, could you share some screenshots of the integration working as well? I've been browsing around the Aureum page and there's nothing there, not even screenshots of the real app itself (without the integration).

**Comment by hutsonphd** [comment]
@rosa : Do these screenshots meet the need?  Thanks! Andrew

**Comment by hutsonphd** [comment]
Hi @rosa   Checking back to see if u need anything else.

**Comment by hutsonphd** [comment]
Hi @rosa Checking back to see if u need anything else.

**Comment by hutsonphd** [comment]
@rosa do you need anything more from me to approve this integration?

**Comment by rosa** [comment]
Hey @hutsonphd, sorry for the delay. Could you update the URL to point to `https://www.aureumdata.com/integrations`?

**Comment by hutsonphd** [comment]
@rosa Done 👍

**Comment by hutsonphd** [comment]
@rosa Awesome! When can we expect to see Aureum listed on Basecamp's website?

**Comment by rosa** [comment]
@hutsonphd, it should be there shortly!

**Pull request merged**
