### PR TITLE
Update integrations.yml and add Apideck

### PR DESCRIPTION
**Pull request by Gdewilde**
Add Apideck to the developer tools section

### CODE REVIEW

**Comment by Gdewilde** [comment]
Thanks, Jose.

**Comment by josefarias** [comment]
@Gdewilde thanks for the PR! I see your site has an outdated Basecamp logo:
Outdated Basecamp logo

Would be great if you could update to the latest which can be found here: https://basecamp.com/press

Feel free to reach out to support if you need other resources: https://basecamp.com/support

**Review by josefarias — CHANGES_REQUESTED** [review]
@Gdewilde before I merge this, could you please upload a different icon that's 256x256, please? Per our guidelines in the readme:

> Add your icon file to the [icons/](https://github.com/basecamp/bc3-integrations/blob/master/icons) folder. Icons must be 256x256 in .png format.

**Comment by Gdewilde** [comment]
Done!

**Comment by josefarias** [comment]
Thanks! Also spotted on the main page:

CleanShot 2023-12-07 at 13 52 24

---

CleanShot 2023-12-07 at 13 51 47

**Comment by Gdewilde** [comment]
Thanks for flagging 🙌🏻 We will get them updated.

**Pull request merged**
