### PR TITLE
BSyncPro3 - Basecamp3 to Salesforce integration details added

### PR DESCRIPTION
**Pull request by timelineiqdev**
Basecamp3 to Salesforce integration - similar to BSync solution listed on the Basecamp 2 extras @ https://basecamp.com/2/extras

### CODE REVIEW

**Comment by jimmackenzie** [comment]
@timelineiqdev your logo looks a little squished there. Do you want to look at adjusting the file to fit 256x256 a little better?

**Comment by timelineiqdev** [comment]
Updated the logo file to match the one on the BC2 extras page. Can you please merge this one - after consulting my team this looks final one.

**Comment by jeremy** [comment]
Merged @ 29dd361b335d0481107d0c6bcbf8aed99ee99f14 with corrected YAML formatting.

**Comment by jeremy** [comment]
Reverted @ 27ef466eb0faa14f8f637d1a8bafc5704cdd9612. The logo image is too small. Tests didn't catch it because they YAML was incorrectly formatted.

**Comment by timelineiqdev** [comment]
sorry - we have added a correct 256X256 logo now -- it should be good now.

**Comment by timelineiqdev** [comment]
Hi Jeremy,

What is the issue with YAML formatting. I see, entries on top and below of
our's are already published with same formatting unless I'm missing
something.

Sincerely,
Kumar,
TimelineIQ

**Comment by jeremy** [comment]
You're missing the separator between entries, causing your info to collide
with the previous entry.

Use a YAML parser to take a closer look.

**Comment by timelineiqdev** [comment]
Hey Guys, Any luck here ? Is it good to approve now?

**Pull request merged**
