### PR TITLE
Update integrations.yml

### PR DESCRIPTION
**Pull request by steve500apps**
We have the ready integration with Track.

### CODE REVIEW

**Comment by steve500apps** [comment]
Please accept the commit.

**Comment by steve500apps** [comment]
> Hi @steve500apps! Looks like this pull request is missing the app icon (`track.png`). Also, looking at [the Track integration with Basecamp page](https://track.ly/basecamp), I see that your integration is with Basecamp 2 and not 3, is this correct? This repository is for integrations with Basecamp 3.

Hello Rosa,  Thank you for quick response. You are correct. we are integrated to Basecamp2. Now Please help me with steps to place our Logo on Basecamp2 as hyperlink.

**Comment by rosa** [comment]
👍 Could you add a file with your logo to this pull request? I'll get the info for your integration and the logo from here and will add it to the `/extras` page for Basecamp 2.

**Comment by steve500apps** [comment]
Track Logo png

**Comment by steve500apps** [comment]
> 👍 Could you add a file with your logo to this pull request? I'll get the info for your integration and the logo from here and will add it to the `/extras` page for Basecamp 2.

Hello Rosa, Thank you for replying. i have added the logo to the pull request. please help me with steps if i have not  done it correctly. 
ps.- i am new to GitHub.

**Comment by steve500apps** [comment]
Track png

**Comment by steve500apps** [comment]
Track png

Icon for Track

**Comment by rosa** [comment]
Hey @steve500apps, this is fine! I'll be adding Track details to basecamp.com/2/extras shortly.

**Comment by rosa** [comment]
@steve500apps details about the Track integration has now been added to [the extras page for Basecamp 2](https://basecamp.com/2/extras).

**Comment by rosa** [comment]
@steve500apps just one last thing: you'll notice that your logo looks very small, especially compared to the other logos in the `/extras` page. The reason is that the logos are square but yours doesn't use a lot of the space on top and below:
Screenshot 2019-06-26 at 14 00 00

If you want to change it so that it looks better in that format, feel free to do so, you just need to provide a new version.

**Comment by steve500apps** [comment]
> @steve500apps just one last thing: you'll notice that your logo looks very small, especially compared to the other logos in the `/extras` page. The reason is that the logos are square but yours doesn't use a lot of the space on top and below:
> Screenshot 2019-06-26 at 14 00 00
> 
> If you want to change it so that it looks better in that format, feel free to do so, you just need to provide a new version.

Hello Rosa,

Request you to change the Logo to the one below. Also we wanted to change the title to -" Track.ly by 500apps "

Please do the needful. My apologies for the inconvenience caused.

**Comment by steve500apps** [comment]
Track

**Comment by rosa** [comment]
Perfect, no worries! I'll change it later today.

**Comment by rosa** [comment]
Done! I changed the name to "Track.ly", though, since we don't include info such as "by 500apps" in the integration names.

**Comment by steve500apps** [comment]
> Done! I changed the name to "Track.ly", though, since we don't include info such as "by 500apps" in the integration names.

Dear Rosa,

Thank you for all the help.

We are publishing a Press Release on Thursday this week about our Application Track.ly. This is an exclusive PR, that mentions about both Track.ly and Basecamp2 integrations. We are sure this event can add mileage to both the brands. 

For this exciting Press release I request you to kindly help us with few lines as a write up.
This Press release is timely planned as an exclusive one about our association and I look forward to receive some interesting content that Track.ly can use for the Press Release.

Our Earlier Press Release for your quick reference is as under..

https://www.prweb.com/releases/market_leader_agile_crm_announces_release_of_track_ly_the_time_tracking_app_suited_for_every_businesss_needs/prweb16340951.htm

Request you to help us with the content at the earliest.

**Comment by rosa** [comment]
Hi @steve500apps, sorry! We only add 3rd party integrations to `/extras` but don't do any co-marketing or press releases. Thanks for offering!

**Comment by steve500apps** [comment]
Hello Rosa, 

I hope you are doing well. 

I am writing to you with a request to change the existing description that we have to basecamp-extra page. 

New Description: 

Basecamp 2:
Track.ly by 500apps
Import your projects and to-dos from Basecamp 2 to track your team’s time to boost efficiency and project success.

Basecamp 3:
Track.ly by 500apps
Sync all your Basecamp 3 projects and to-do with Track.ly by 500apps to automate time tracking and increase employee productivity.

Also, would you be able to update this Logo on the page as well?

track ly 256 px

Thank you for your help. Please let us know if anything.

**Comment by rosa** [comment]
Hey @steve500apps, just a few things: 
- The logo attached is 256 × 328 pixels. We can only use square logos, 256 x 256. 
- We can't include "by 500apps" in the title, as we don't include the maker's name in the app names for any other app in `/extras`. 
- I can do this for you one more time, but it'll be the last. For next times, you need to open a pull request in this repository for BC3 integrations like every other integrator does, and not just asking us to do this work.

**Comment by steve500apps** [comment]
Hello Rosa, 

Thank you so much for your help and sorry for the inconvenience caused. 

Attached is the 256x256 logo. Hope this would be good. 
track ly 256256– 2

**Comment by rosa** [comment]
Cool, thank you for the updated logo, that's one is correct! I've pushed the updates for both BC3 and BC2's `/extras` pages 😃

**Comment by steve500apps** [comment]
Thank you so much Rosa. Appreciate all your assistance with this.

**Pull request closed without merging**
