### PR TITLE
Submitting Intro CRM for inclusion in Basecamp 3 integrations list.

### PR DESCRIPTION
**Pull request by kenhara**
This pull request is to submit my SaaS Intro CRM for inclusion in the [Basecamp 3 integrations list](https://basecamp.com/extras). If there's anything I need to update or change, please just let me know. Thank you! – Harris

### CODE REVIEW

**Review by rosa — CHANGES_REQUESTED** [review]
Hey @kenhara, thanks for sending this PR! Would you mind moving your entry in the `integrations.yml` file to the end of the file? Apart from that, everything looks perfect.

**Review by kenhara — COMMENTED** [review]
@rosa Hopefully I did that right, please let me know–thanks so much!

**Review by rosa — APPROVED** [review]
Yes, that's perfect! Thank you so much.

**Comment by rosa** [comment]
Just one last thing before I can merge: can you resolve the conflicts after merging the `master` branch?

**Review by kenhara — COMMENTED** [review]
Updating to include newly added Honeybadger in integrations.yaml

**Comment by kenhara** [comment]
> Just one last thing before I can merge: can you resolve the conflicts after merging the `master` branch?

@rosa Should be good now! I just had to update to include the new Honeybadger listing

**Comment by rosa** [comment]
Great, thank you so much, @kenhara!

**Pull request merged**
