### PR TITLE
Add Ganttify

### PR DESCRIPTION
**Pull request by rvanbaalen**
Add Ganttify to the integration partner list

### CODE REVIEW

**Comment by javan** [comment]
https://www.ganttify.com/ doesn't load for me. http://www.ganttify.com/ does and redirects to https://www.gantt-chart.com/. What's the correct URL?

**Comment by rvanbaalen** [comment]
@javan Sorry about that. Ganttify is the name of our application, www.gantt-chart.com is the operational domain name (for SEO purposes).

You can go ahead and make https://www.gantt-chart.com/ the leading domain if you want.

**Comment by javan** [comment]
Please update this PR with a working URL :)

**Comment by rvanbaalen** [comment]
There you go. Should be good now?

**Pull request merged**
