### PR TITLE
how to get verification code in integration of Basecamp?

### PR DESCRIPTION
**Pull request by ghost**
Hey, 

We are doing an integration of Basecamp to our apps. but after "Yes I'll allow access" button click I am stuck at step 3: We redirect the user back to your app with a time-limited verification code. this "verification code" inside iframe window URL. how we get this code as you know can't access iframe URL.

Getting verification code we need to pass it on URL like this: 
https://launchpad.37signals.com/authorization/token?type=web_server&client_id=your-client-id&redirect_uri=your-redirect-uri&client_secret=your-client-secret&code=verification-code

my question is how do we get verification code from IFrame URL. or do you have any other to do step 4? 

currently, we are unable to get integration to out app.

we follow steps from GitHub see below: https://github.com/basecamp/api/blob/master/sections/authentication.md

Please help us.

Thanks,
Vaishali.

### CODE REVIEW

**Comment by rosa** [comment]
@vaishaligarg2014 have you tried without using any iframes? That is, simply follow the steps by redirecting the user to Launchpad first, and then when we redirect the user back to your app, you just grab the time-limited verification code from the request, and use it in the backchannel request to us. You don't need to use an iframe in any of these steps.

**Comment by vaishaligarg2014** [comment]
Sure, Thanks @rosa 
one more thing, Can you please tell me how to I grab the code. the window is not the same when redirecting. so we will get the verification code.

by the way thanks for your suggestion.

**Comment by rosa** [comment]
No problem! So, when you register your application, you need to specify a redirect URI, where we'll redirect the user on step 3, with the code:
screen shot 2018-09-18 at 17 10 33

Using that URL as example, on step 3, we'll redirect the user to `https://myapp.com/auth?code=XXX`. Your app will receive a GET request from the user, then, with `code` as query parameter. You just read it from there. 

I hope this helps!

**Comment by vaishaligarg2014** [comment]
Thank you so much.
This will help me. I will do the same.
Thanks, once again for your time.

**Comment by rosa** [comment]
@vaishaligarg2014 no problem, best of luck with the implementation! 😄

**Pull request closed without merging**
