### PR TITLE
Social media integration for BC3

### PR DESCRIPTION
**Pull request by chribsen**
I've created a Social media notification tool for BC3 that I would like to get listed on https://basecamp.com/extras.

### CODE REVIEW

**Comment by javan** [comment]
Looks like the logo file you added is too big. We expect 256x256 and yours is 1460x1370.

**Comment by chribsen** [comment]
Thanks. I've changed the size to 256x256 now. Looks like all checks passed this time.

**Comment by javan** [comment]
Thanks! Might be worth noting on your site that the integration is for Basecamp 3 specifically. There are still many active Basecamp 1 and 2 users.

**Comment by chribsen** [comment]
I'll make sure to mention it as "Basecamp 3" on the page. Thanks for the reminder.
How many are using 1 and 2 approximately? And when will the changes propagate to the /extras page?

**Comment by jeremy** [comment]
Up now at https://basecamp.com/extras 👍

**Pull request merged**
