### PR TITLE
Add Track.ly integration

### PR DESCRIPTION
**Pull request by rosa**
Replaces https://github.com/basecamp/bc3-integrations/pull/127

/cc @steve500apps

### CODE REVIEW

**Comment by steve500apps** [comment]
> Replaces #127
> 
> /cc @steve500apps



Hello Rosa,
Greetings!!!

We are providing Basecamp3 ready integration with Track.ly. Request you to publish our logo to https://basecamp.com/extras.
Below is the link to see the integration provided by Track.ly.
Link - https://track.ly/basecamp3-integration

Please do the neeful.

**Comment by rosa** [comment]
You should see the integration in the `/extras` page now!

**Comment by steve500apps** [comment]
> You should see the integration in the `/extras` page now, sorry for the delay

Thank you.
Request you to change the description.
description :  "Boost team productivity with automatic time tracking software, online timesheets, activity screenshots, project budgeting, payroll integration and more."
Sorry for the trouble.

**Comment by rosa** [comment]
@steve500apps feel free to submit a pull request with that change and any other you want for your integration 😄

**Pull request merged**
