### PR TITLE
Add slickplan.com to /extras

### PR DESCRIPTION
**Pull request by PawelAwmous**
Here is a short instruction of how the integration on Slickplan works: https://help.slickplan.com/hc/en-us/articles/203479454 Thanks!

### CODE REVIEW

**Comment by javan** [comment]
Does your integration work with Basecamp 3? https://help.slickplan.com/hc/en-us/articles/203479454 and https://help.slickplan.com/hc/en-us/articles/202487020 only make reference Basecamp 1 and 2.

**Comment by PawelAwmous** [comment]
Sure it does! We actually support all Basecamp versions. [Here](https://help.slickplan.com/hc/en-us/articles/202487020) you can see we allow our customers to choose a version of their account: "Classic" is for v1 (API key), and "New" is for v2 and v3 (oAuth)

**Comment by javan** [comment]
Got it. I wasn't sure if "New" meant Basecamp 2 because all the screenshots on https://help.slickplan.com/hc/en-us/articles/203479454 are from Basecamp 2. You may want to consider changing "New" to "Basecamp 2 - 3" or something similar. That's how we label them on https://basecamp.com/help.

**Comment by PawelAwmous** [comment]
Thanks! I’m gonna add your note to our kanban board for future updates. I think we're going to change the screenshots as well, we will be updating our knowledgebase soon, and the Basecamp 3 is currently the most popular version our customers use. Thanks again!

**Pull request merged**
