### PR TITLE
Add AgencyDots to the integrations

### PR DESCRIPTION
**Pull request by amavica**

### CODE REVIEW

**Review by lewispb — CHANGES_REQUESTED** [review]
Thanks @amavica. Please let us know when the product is live, and beyond just a wait list.

**Comment by amavica** [comment]
Hello,

The product is live and stable. The waiting list is only a marketing
campaign.
You can register here: https://app.agencydots.com

Best,

**Comment by lewispb** [comment]
I've signed up, but can't see how to integrate with Basecamp.

**Comment by amavica** [comment]
At the top right, click on your photo and then "Profile".
Choose the tab "Integrations" and there you can connect.

**Comment by lewispb** [comment]
Ah, thanks @amavica.

The integration doesn't seem to be working. I get an error:

`:error: Provided redirect_uri is not approved`

**Comment by amavica** [comment]
Sorry about that.
Now it's fixed.

Best,

**Comment by lewispb** [comment]
Thanks. Please rebase and then I will merge this.

**Comment by amavica** [comment]
I think it's ready now.

Best,

**Pull request merged**
