### PR TITLE
Add Time Tracker, Todo, Sprint Manager - Basecamp in listing

### PR DESCRIPTION
**Pull request by MosamMTL**
This Simplest Basecamp Extension for keep your work synced with Moon HRM, also you can use multiple features like mange status, spent , estimated hours , manage sprint  and enhanced functionality in basecamp

### CODE REVIEW

**Comment by MosamMTL** [comment]
Sync daily tasks or work between Basecamp & Moon HRM. Use filters & enhanced features for seamless collaboration.

**Comment by PC2CJ** [comment]
Hi @ramhoj 

> However, we can't add the Moon Apps Basecamp Extension to our integration lists as it falls under the "employee surveillance software" category of apps due to its integration with Moon HRM. In particular, these features from your website:
> Employee Tracking – Track all the employee activities and get screenshots for the same.
> Screen Monitoring – View employee screen and monitor it when they turn on the In-Out timer.

Thank you for your quick response and for bringing this thing to our attention. We totally respect your terms of service and privacy policy. 

> Here is a short excerpt from our terms of service:
> Third parties may not access and employ the API if the functionality is part of an application that remotely records, monitors, or reports a Service user's activity other than time tracking, both inside and outside the applications.
> You can read more about our decision to not allow employee-surveillance software integrations [here](https://m.signalvnoise.com/employee-surveillance-software-is-not-welcome-to-integrate-with-basecamp/).

Actually "Time Tracker, Todo, Sprint Manager - Basecamp" is not employee surveillance software. We built an extension to smoothen Basecamp features. Here in extension, we are not tracking any employee's activity or screenshots or screen monitoring via our Basecamp extension. 

From Basecamp extension we provided Various Filter and shorting Options, also integrated with our HRM and Invoice software to log hours for Estimate and total Hours Management and to check work reports. Here in this process, we are not capturing any activity or screenshots or screen monitoring.

As you have seen tracking activity or screenshots or screen monitoring is required our separate HRM desktop application. This is an add-on feature for our HRM with desktop applications only.

We are not using a desktop application for Basecamp extension. So it will not harm your terms of service and privacy policy. 

So we are requesting you to approve our basecamp extension for Basecamp Extra page. And we will take care of your terms of service and privacy policy. 

> Also note that you are required to have written permission to use our logo for promotional purposes as being done in the screenshots shown on https://www.moonapps.xyz/basecamp-extension/. Unless you've already received this permission please send a request to [support@basecamp.com](mailto:support@basecamp.com).

Sorry for the inconvenience, we will take care of it and will send an email request for approval.

**Comment by ramhoj** [comment]
Thank you for clarifying how you are planning on using the Basecamp integration and for your understanding of our terms of service @PC2CJ.

Unfortunately the terms aren't limited to whether the extension itself is executing employee surveillance, it's enough that:
> part of an application … reports a Service user’s activity…

This is further clarified by our CTO David Heinemeier Hansson [here](https://m.signalvnoise.com/employee-surveillance-software-is-not-welcome-to-integrate-with-basecamp/):

> In other words, we’ve moved to ban employee surveillance vendors from integrating with Basecamp, and to use Basecamp’s logo under any circumstances. 

I urge you to read [the full blog post](https://m.signalvnoise.com/employee-surveillance-software-is-not-welcome-to-integrate-with-basecamp/) for a clearer understanding of our chose to saying no to employee surveillance.

**Comment by PC2CJ** [comment]
@ramhoj 

Thank you again for your quick response. 

As per your guidelines, we removed all features that were breaking privacy policy related to employee surveillance.

You can verify our integration site here https://hrm.moonapps.xyz/ too.

"Time Tracker, Todo, Sprint Manager - Basecamp" is main to uses Various Filter and shorting Options, also integrated with our HRM and Invoice software to log hours for Estimate and total Hours Management and to check work reports. 

Now we are not tracking any employee's activity and not monitoring it. 

Also, we removed your logo which we used on our website. 

So kindly request you to approve our extension.

**Comment by PC2CJ** [comment]
@ramhoj Thank you for your valuable suggestion.

We made changes in a category and changed it to category 2 now.

We requested pull again so please do needful and request you to approve it.

**Comment by PC2CJ** [comment]
OK thank you very much.

May I know when it can be visible here https://basecamp.com/extras

And what is process?

**Comment by ramhoj** [comment]
Hey @PC2CJ, sorry for not spotting this earlier but could you consider updating the title to fit on one line on the the extras page?

Screenshot 2023-09-06 at 15 00 28

Most other integrations has their product name as the title. I would suggest re-working the description to incorporate the most important information while keeping at 2 or 3 lines. Here is a suggestion to illustrate how it would fit better on the extras page:

Screenshot 2023-09-06 at 15 08 24

**Comment by PC2CJ** [comment]
@ramhoj Thank you for the suggestions.
We made changes here https://github.com/basecamp/bc3-integrations/pull/214

**Comment by ramhoj** [comment]
> May I know when it can be visible here https://basecamp.com/extras

Good day @PC2CJ, the Moon HRM Integration is now displayed on https://basecamp.com/extras 🎉.

**Comment by PC2CJ** [comment]
Thank you very much.

**Pull request merged**
